name: AternixMC
version: 1.21.11
main: com.aternixmc.moderation.AternixMC
api-version: '1.21'
author: Mattia Lascaro
description: Sistema di moderazione 

permissions:
  aternixmc.staff:
    description: Permette di vedere le notifiche dello staff.
    default: op

commands:
  ban: { permission: aternixmc.ban }
  tempban: { permission: aternixmc.tempban }
  ipban: { permission: aternixmc.ipban }
  tempipban: { permission: aternixmc.tempipban }
  unban: { permission: aternixmc.unban }
  mute: { permission: aternixmc.mute }
  tempmute: { permission: aternixmc.tempmute }
  unmute: { permission: aternixmc.unmute }
  kick: { permission: aternixmc.kick }
  warn: { permission: aternixmc.warn }
  tempwarn: { permission: aternixmc.tempwarn }
  unwarn: { permission: aternixmc.unwarn }
  check: { permission: aternixmc.check }
  history: { permission: aternixmc.history }
  dupeip: { permission: aternixmc.dupeip }
  clearchat: { permission: aternixmc.clearchat }
  mutechat: { permission: aternixmc.mutechat }
